services:
  # Laravelバックエンド
  - type: web
    name: pocket-money-api
    env: docker
    plan: free
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: pocket-money-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

  # React フロントエンド
  - type: web
    name: pocket-money-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pocket-money-api.onrender.com

databases:
  - name: pocket-money-db
    plan: free
    databaseName: pocket_money
    user: pocket_money_user
